
import sys

file_path = r'd:\studlyf\frontend\components\institution\PostOpportunityModal.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# We need to find the specific marker for the end of Step 2 platform section.
# Line 864: Redirect candidates to an external website.

start_index = -1
for i, line in enumerate(lines):
    if "Redirect candidates to an external website." in line:
        start_index = i
        break

if start_index == -1:
    print("Could not find start marker.")
    sys.exit(1)

# We will replace from start_index+1 until the end of the return block.
# We need to find where the return block effectively ends.
end_marker = "export default PostOpportunityModal;"
end_index = -1
for i in range(len(lines)-1, 0, -1):
    if end_marker in lines[i]:
        end_index = i
        break

if end_index == -1:
    print("Could not find end marker.")
    sys.exit(1)

# Reconstruct the entire tail with perfect hierarchy
new_tail = [
    '                                                            <p className="text-xs text-slate-300 font-medium mt-1">Redirect candidates to an external website.</p>\n',
    '                                                        </div>\n',
    '                                                    </div>\n',
    '                                                </div>\n',
    '                                            </div>\n',
    '                                        </div>\n',
    '                                    </div>\n',
    '                            )}\n',
    '                        </div>\n',
    '                    </div>\n',
    '\n',
    '                    <div className="p-8 border-t border-slate-100 bg-white flex items-center justify-end gap-4 shrink-0">\n',
    '                        <button onClick={handleSaveDraft} className="px-8 py-3.5 bg-slate-50 text-slate-500 rounded-full font-bold text-sm hover:bg-slate-100 transition-all border border-slate-100">Save as Draft</button>\n',
    '                        <button \n',
    '                            disabled={loading}\n',
    '                            onClick={handleNext} \n',
    '                            className={`px-8 py-3.5 bg-[#6C3BFF] text-white rounded-full font-bold text-sm transition-all flex items-center gap-3 ${loading ? "opacity-50 cursor-not-allowed" : "hover:shadow-xl hover:shadow-purple-200"}`}\n',
    '                        >\n',
    '                            <span>{loading ? "Processing..." : (step === 2 ? "Publish" : "Save and next")}</span>\n',
    '                            <ChevronRight size={18} />\n',
    '                        </button>\n',
    '                    </div>\n',
    '                </div>\n',
    '            </motion.div>\n',
    '        </div>\n',
    '\n',
    '        {/* Add Questions Sub-modal */}\n',
    '            <AnimatePresence>\n',
    '                {isAddingQuestion && (\n',
    '                    <>\n',
    '                    <div className="fixed inset-0 z-[300] flex items-center justify-center p-4">\n',
    '                        <motion.div \n',
    '                            initial={{ opacity: 0 }}\n',
    '                            animate={{ opacity: 1 }}\n',
    '                            exit={{ opacity: 0 }}\n',
    '                            onClick={() => { setIsAddingQuestion(false); setSelectedFieldType(null); }}\n',
    '                            className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" \n',
    '                        />\n',
    '                        <motion.div \n',
    '                            initial={{ scale: 0.9, opacity: 0, y: 20 }}\n',
    '                            animate={{ scale: 1, opacity: 1, y: 0 }}\n',
    '                            exit={{ scale: 0.9, opacity: 0, y: 20 }}\n',
    '                            className="relative w-full max-w-xl bg-white rounded-[1.5rem] shadow-2xl overflow-hidden font-[\'Outfit\']"\n',
    '                        >\n',
    '                            <div className="p-6 border-b border-slate-100 flex items-center justify-between">\n',
    '                                <div>\n',
    '                                    <h3 className="text-xl font-black text-slate-900">Add Questions</h3>\n',
    '                                    <p className="text-xs text-slate-400 font-medium mt-1">Ask candidates custom questions when they register.</p>\n',
    '                                </div>\n',
    '                                <button onClick={() => { setIsAddingQuestion(false); setSelectedFieldType(null); }} className="p-2 hover:bg-slate-50 rounded-full text-slate-400">\n',
    '                                    <X size={20} />\n',
    '                                </button>\n',
    '                            </div>\n',
    '\n',
    '                            <div className="p-8 max-h-[70vh] overflow-y-auto custom-scrollbar">\n',
    '                                {!selectedFieldType ? (\n',
    '                                    <div className="space-y-6">\n',
    '                                        <p className="text-[11px] font-black text-slate-400 uppercase tracking-widest">Custom</p>\n',
    '                                        <div className="grid grid-cols-2 gap-4">\n',
    '                                            {[\n',
    '                                                { id: "few_words", label: "Few Words (Text Box)", icon: "✏️" },\n',
    '                                                { id: "paragraph", label: "Paragraph (Text Area)", icon: "📝" },\n',
    '                                                { id: "radio", label: "Radio Button", icon: "🔘" },\n',
    '                                                { id: "checkbox", label: "Check Box", icon: "☑️" },\n',
    '                                                { id: "dropdown", label: "Dropdown", icon: "🔽" },\n',
    '                                                { id: "file", label: "File", icon: "📤" },\n',
    '                                                { id: "accept", label: "Accept Box (E.g. Accept Terms)", icon: "👍" }\n',
    '                                            ].map(type => (\n',
    '                                                <button \n',
    '                                                    key={type.id}\n',
    '                                                    onClick={() => setSelectedFieldType(type.id)}\n',
    '                                                    className="flex items-center gap-4 p-4 bg-slate-50 border border-slate-100 rounded-2xl hover:border-[#6C3BFF] hover:bg-white hover:shadow-lg hover:shadow-purple-50 transition-all text-left"\n',
    '                                                >\n',
    '                                                    <div className="w-10 h-10 bg-orange-500 rounded-xl flex items-center justify-center text-white text-lg shadow-sm">\n',
    '                                                        {type.icon}\n',
    '                                                    </div>\n',
    '                                                    <span className="text-[13px] font-bold text-slate-700 leading-tight">{type.label}</span>\n',
    '                                                </button>\n',
    '                                            ))}\n',
    '                                        </div>\n',
    '                                    </div>\n',
    '                                ) : (\n',
    '                                    <div className="space-y-8 animate-in slide-in-from-right-4 duration-300">\n',
    '                                        <div className="flex items-center justify-between">\n',
    '                                            <div className="flex items-center gap-3 px-4 py-2 bg-orange-100 text-orange-600 rounded-xl">\n',
    '                                                <span className="text-lg">⚙️</span>\n',
    '                                                <span className="text-xs font-black uppercase tracking-widest">{selectedFieldType.replace("_", " ")}</span>\n',
    '                                            </div>\n',
    '                                            <div className="w-10 h-10 border-2 border-[#6C3BFF] rounded-xl flex items-center justify-center text-[#6C3BFF]">\n',
    '                                                <Lock size={18} />\n',
    '                                            </div>\n',
    '                                        </div>\n',
    '\n',
    '                                        <div className="space-y-6">\n',
    '                                            <div>\n',
    '                                                <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Field Label *</label>\n',
    '                                                <input \n',
    '                                                    type="text" \n',
    '                                                    placeholder="Enter question label"\n',
    '                                                    className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl focus:ring-2 focus:ring-[#6C3BFF]/20 outline-none font-medium text-sm"\n',
    '                                                />\n',
    '                                            </div>\n',
    '\n',
    '                                            {(selectedFieldType === "radio" || selectedFieldType === "checkbox" || selectedFieldType === "dropdown") && (\n',
    '                                                <div className="space-y-4">\n',
    '                                                    <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest">Options</label>\n',
    '                                                    {newFieldConfig.options.map((opt, i) => (\n',
    '                                                        <div key={i} className="flex gap-3">\n',
    '                                                            <input \n',
    '                                                                type="text" \n',
    '                                                                placeholder={`Option ${i+1}`}\n',
    '                                                                className="flex-1 px-5 py-3 bg-white border border-slate-100 rounded-xl focus:border-[#6C3BFF] outline-none text-sm"\n',
    '                                                            />\n',
    '                                                            {i > 0 && <button className="text-slate-300 hover:text-red-500 transition-all">✕</button>}\n',
    '                                                        </div>\n',
    '                                                    ))}\n',
    '                                                    <button \n',
    '                                                        onClick={() => setNewFieldConfig({...newFieldConfig, options: [...newFieldConfig.options, ""]})}\n',
    '                                                        className="text-[11px] font-black text-[#6C3BFF] uppercase tracking-widest flex items-center gap-2"\n',
    '                                                    >\n',
    '                                                        <Plus size={14} /> Add another Options\n',
    '                                                    </button>\n',
    '                                                </div>\n',
    '                                            )}\n',
    '\n',
    '                                            {selectedFieldType === "file" && (\n',
    '                                                <div>\n',
    '                                                    <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Max. file size allowed for upload (In MB) ? *</label>\n',
    '                                                    <input \n',
    '                                                        type="number" \n',
    '                                                        defaultValue={50}\n',
    '                                                        className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl outline-none font-bold text-sm"\n',
    '                                                    />\n',
    '                                                </div>\n',
    '                                            )}\n',
    '\n',
    '                                            {selectedFieldType === "accept" && (\n',
    '                                                <div>\n',
    '                                                    <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Check Box Text *</label>\n',
    '                                                    <input \n',
    '                                                        type="text" \n',
    '                                                        placeholder="I accept the terms and conditions"\n',
    '                                                        className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl outline-none font-medium text-sm"\n',
    '                                                    />\n',
    '                                                </div>\n',
    '                                            )}\n',
    '\n',
    '                                            <div>\n',
    '                                                <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Remark/Hint</label>\n',
    '                                                <input \n',
    '                                                    type="text" \n',
    '                                                    placeholder="Enter the hint/remarks for this field if any."\n',
    '                                                    className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl outline-none font-medium text-sm"\n',
    '                                                />\n',
    '                                            </div>\n',
    '\n',
    '                                            <div>\n',
    '                                                <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Custom Error Message</label>\n',
    '                                                <input \n',
    '                                                    type="text" \n',
    '                                                    placeholder="Enter custom error message (optional)"\n',
    '                                                    className="w-full px-5 py-4 bg-white border border-[#6C3BFF] rounded-xl outline-none font-medium text-sm"\n',
    '                                                />\n',
    '                                            </div>\n',
    '                                        </div>\n',
    '                                    </div>\n',
    '                                )}\n',
    '                            </div>\n',
    '\n',
    '                            <div className="p-6 border-t border-slate-100 bg-slate-50/50 flex items-center justify-between">\n',
    '                                <button \n',
    '                                    onClick={() => { setSelectedFieldType(null); if(!selectedFieldType) setIsAddingQuestion(false); }}\n',
    '                                    className="px-6 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-500 hover:bg-slate-50 transition-all"\n',
    '                                >\n',
    '                                    Cancel\n',
    '                                </button>\n',
    '                                {selectedFieldType && (\n',
    '                                    <button \n',
    '                                        onClick={() => { setIsAddingQuestion(false); setSelectedFieldType(null); }}\n',
    '                                        className="px-8 py-2.5 bg-[#6C3BFF] text-white rounded-xl text-xs font-bold hover:shadow-lg hover:shadow-purple-200 transition-all"\n',
    '                                    >\n',
    '                                        Save\n',
    '                                    </button>\n',
    '                                )}\n',
    '                            </div>\n',
    '                        </motion.div>\n',
    '                    </div>\n',
    '                    </>\n',
    '                )}\n',
    '            </AnimatePresence>\n',
    '\n',
    '            {/* Get in Touch Sidebar Drawer */}\n',
    '            <AnimatePresence>\n',
    '                {isSupportDrawerOpen && (\n',
    '                    <>\n',
    '                        <motion.div \n',
    '                            initial={{ opacity: 0 }}\n',
    '                            animate={{ opacity: 1 }}\n',
    '                            exit={{ opacity: 0 }}\n',
    '                            onClick={() => setIsSupportDrawerOpen(false)}\n',
    '                            className="fixed inset-0 z-[400] bg-slate-900/40 backdrop-blur-sm"\n',
    '                        />\n',
    '                        <motion.div \n',
    '                            initial={{ x: "100%" }}\n',
    '                            animate={{ x: 0 }}\n',
    '                            exit={{ x: "100%" }}\n',
    '                            transition={{ type: "spring", damping: 25, stiffness: 200 }}\n',
    '                            className="fixed right-0 top-0 bottom-0 w-[450px] bg-white z-[450] shadow-2xl flex flex-col font-[\'Outfit\']"\n',
    '                        >\n',
    '                            <div className="p-8 border-b border-slate-100 flex items-center justify-between">\n',
    '                                <h3 className="text-xl font-black text-slate-900">Get in touch</h3>\n',
    '                                <button onClick={() => setIsSupportDrawerOpen(false)} className="p-2 hover:bg-slate-100 rounded-full text-slate-400 transition-all">\n',
    '                                    <X size={20} />\n',
    '                                </button>\n',
    '                            </div>\n',
    '\n',
    '                            <div className="flex-1 overflow-y-auto p-8 space-y-8 custom-scrollbar">\n',
    '                                <div className="space-y-6">\n',
    '                                    <div>\n',
    '                                        <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Name *</label>\n',
    '                                        <input type="text" placeholder="Enter your name" className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl focus:ring-2 focus:ring-[#6C3BFF]/20 outline-none text-sm font-medium" />\n',
    '                                    </div>\n',
    '                                    <div>\n',
    '                                        <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Email ID *</label>\n',
    '                                        <input type="email" placeholder="Enter your email" className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl focus:ring-2 focus:ring-[#6C3BFF]/20 outline-none text-sm font-medium" />\n',
    '                                    </div>\n',
    '                                    <div>\n',
    '                                        <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Mobile No. *</label>\n',
    '                                        <div className="flex gap-2">\n',
    '                                            <div className="px-4 py-4 bg-slate-100 border border-slate-100 rounded-xl text-sm font-black text-slate-500">+91</div>\n',
    '                                            <input type="text" placeholder="Mobile Number" className="flex-1 px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl focus:ring-2 focus:ring-[#6C3BFF]/20 outline-none text-sm font-medium" />\n',
    '                                        </div>\n',
    '                                    </div>\n',
    '                                    <div>\n',
    '                                        <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Organisation *</label>\n',
    '                                        <input type="text" placeholder="Enter organization name" className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl focus:ring-2 focus:ring-[#6C3BFF]/20 outline-none text-sm font-medium" />\n',
    '                                    </div>\n',
    '                                    <div>\n',
    '                                        <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest mb-2">Please describe the issue which you are facing *</label>\n',
    '                                        <select className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl outline-none text-sm font-medium appearance-none mb-4">\n',
    '                                            <option>Please select interest</option>\n',
    '                                            <option>Technical Issue</option>\n',
    '                                            <option>Registration Query</option>\n',
    '                                            <option>Billing/Pricing</option>\n',
    '                                            <option>Others</option>\n',
    '                                        </select>\n',
    '                                        <textarea \n',
    '                                            rows={4}\n',
    '                                            placeholder="Tell us more about your issue..."\n',
    '                                            className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-xl focus:ring-2 focus:ring-[#6C3BFF]/20 outline-none text-sm font-medium resize-none"\n',
    '                                        />\n',
    '                                    </div>\n',
    '                                </div>\n',
    '                            </div>\n',
    '\n',
    '                            <div className="p-8 border-t border-slate-100">\n',
    '                                <button className="w-full py-4 bg-[#6C3BFF] text-white rounded-xl font-black text-xs uppercase tracking-widest hover:shadow-xl hover:shadow-purple-200 transition-all">Submit</button>\n',
    '                            </div>\n',
    '                        </motion.div>\n',
    '                    </>\n',
    '                )}\n',
    '            </AnimatePresence>\n',
    '        </>\n',
    '    );\n',
    '};\n',
    '\n',
    'export default PostOpportunityModal;\n'
]

# Write back the file
final_lines = lines[:start_index] + new_tail
with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(final_lines)

print("Successfully rebuilt the component tail with correct JSX hierarchy.")
